spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      grid-fs-database: images
    jackson:
      default-property-inclusion: non_null
      serialization:
        indent-output: true
  logging:
    level:
      root: INFO
      sql: DEBUG
      web: TRACE
      com.example: DEBUG
      org.springframework.security: DEBUG
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
server:
  port: 0
