spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      grid-fs-database: images
    jackson:
      default-property-inclusion: non_null
      serialization:
        indent-output: true
  security:
    user:
      name: user # Default user name.
      password: pass # Password
      roles: admin,owner # A comma separated list of roles
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
server:
  port: 0
