eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    tracing:
        sampling:
            probability: 1
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans/
server:
    port: 0
spring:
    application:
        name: notification-service
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: notificationId
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            properties:
                spring:
                    json:
                        type:
                            mapping: event:org.mwashi_mwale.SearchEvent
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        template:
            default-topic: notificationTopic
