eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    tracing:
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
server:
    port: 0
spring:
    application:
        name: version_control_service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: mysql
        url: jdbc:mysql://localhost:3306/version_control_service
        username: root
    jpa:
        hibernate:
            ddl-auto: update
