app:
    eureka-server: localhost
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka
logging:
    pattern:
        level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
management:
    endpoints:
        web:
            exposure:
                include: prometheus
    tracing:
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://localhost:9411/api/v2/spans
server:
    port: 8181
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
            -   id: auth
                predicates:
                -  Path=/api/auth
                uri: lb://auth
            -   id: notifications
                predicates:
                -  Path=/api/notifications
                uri: lb://notification
            -   id: version-control
                predicates:
                -  Path=/api/version-control
                uri: lb://version-control
            -   id: documents-service
                predicates:
                - Path=/api/documents
                uri: lb://documents-service
            -   id: searching-service
                predicates:
                - Path=/api/searching
                uri: lb://searching-service
            -   filters:
                - SetPath=/
                id: discovery-server
                predicates:
                - Path=/eureka/web
                uri: http://eureka:password@${app.eureka-server}:8761
            -   id: discovery-server-static
                predicates:
                - Path=/eureka/**
                uri: http://eureka:password@${app.eureka-server}:8761
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8585/realms/hosdocs_realm
